# Generated by Django 5.1.7 on 2025-03-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужчины'), ('F', 'Женщины')], default='M', max_length=1),
        ),
    ]
